export const clientProjects = [
  {
    client: "Emma Wilson",
    country: "Canada",
    email: "emma.wilson@example.com",
    project: "Maple CRM",
    progress: "72%",
    status: "Active",
    date: "2025-07-15",
    image: "https://source.unsplash.com/random/50x50/?woman,portrait",
  },
  {
    client: "Liam Smith",
    country: "United Kingdom",
    email: "liam.smith@example.co.uk",
    project: "E-Commerce Revamp",
    progress: "45%",
    status: "Pending",
    date: "2025-06-28",
    image: "https://source.unsplash.com/random/50x50/?man,portrait",
  },
  {
    client: "Sophia Martinez",
    country: "Spain",
    email: "sophia.martinez@example.es",
    project: "Tourist App Redesign",
    progress: "100%",
    status: "Completed",
    date: "2025-07-05",
    image: "https://source.unsplash.com/random/50x50/?female,profile",
  },
  {
    client: "Noah Kim",
    country: "South Korea",
    email: "noah.kim@example.kr",
    project: "Smart Home Dashboard",
    progress: "30%",
    status: "Active",
    date: "2025-07-23",
    image: "https://source.unsplash.com/random/50x50/?male,profile",
  },
  {
    client: "Olivia Johnson",
    country: "USA",
    email: "olivia.johnson@example.com",
    project: "Healthcare Portal",
    progress: "85%",
    status: "Active",
    date: "2025-07-11",
    image: "https://source.unsplash.com/random/50x50/?woman,face",
  },
];
